// Re-export Database type from the canonical source (supabase/types/database.types.ts).
// Do NOT edit the source file — it is auto-generated by the Supabase CLI.
export type { Database } from '../../../supabase/types/database.types';
